---
etcd_user: etcd
etcd_group: etcd
etcd_install_dir: /usr/local/bin
etcd_data_dir: /var/lib/etcd

etcd_master_group_name: etcd_master

etcd_secure: True
etcd_pki_dir: ~/pki-dir
etcd_pki_key_suffix: -key.pem
etcd_pki_cert_suffix: .pem

etcd_use_ips: True
etcd_network_iface: default

etcd_cluster_name: test-cluster-name
etcd_initial_cluster_token: d8bf8cc6-5158-11e6-8f13-3b32f4935bde

etcd_init_system: systemd
etcd_launch: True
