---

- name: Install pgdg apt key
  apt_key:
    id: ACCC4CF8
    url: http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: Install pgdg repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes

- name: Install debian postgresql utils
  apt:
    name: postgresql-common
    state: present

- name: Disable auto creation of main cluster
  lineinfile:
    path: /etc/postgresql-common/createcluster.conf
    regexp: 'create_main_cluster =.*'
    line: 'create_main_cluster = false'

- name: Install postgresql
  apt:
    name: postgresql-{{ postgresql_version }}
    state: present
