---

- name: Ensure ssh keys are created for postgresql user
  user:
    name: "{{ ssh_user }}"
    generate_ssh_key: yes
    ssh_key_type: "{{ ssh_key_type }}"

- name: Find public ssh keys
  slurp:
    src: "~{{ ssh_user }}/.ssh/id_{{ ssh_key_type }}.pub"
  register: sshkey
