---

- name: Enable and start systemd patroni scripts
  systemd:
    daemon_reload: yes
    name: "patroni-{{ item.key }}"
    enabled: true
    state: started

- name: Wait for patroni server to start
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ item.value.port + 2000 }}"
    delay: 10
    timeout: 300

- name: Apply tuning
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ item.value.port + 2000 }}/config"
    body: "{{ lookup('template','tuning.json') }}"
    body_format: json
    method: "PATCH"
  when: item.value.tuning is defined and item.value.tuning
  run_once: true
