---

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  gather_facts: true
  roles:
    - common
    - elao.locales
#    - upgrade

- hosts: database
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - postgresql
    - etcd
    - etcd-cluster
    - patroni

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - ssh-key-user
    - ssh-hostkey

- hosts: database
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - pgbackrest

- hosts: backup
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - pgbackrest

- hosts: database
  environment: "{{ proxy_env }}"
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - pgbouncer-client

- hosts: frontal
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - pgbouncer
    - confd

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  become_flags: '-E -H'
  any_errors_fatal: true
  roles:
    - { role: cleaner-patroni, when: needcleaning|bool }
