---

- name: Download confd
  get_url:
    url: "{{ confd_url }}"
    checksum: "{{ confd_linux_amd64_checksum }}"
    dest: /usr/local/bin/confd
    owner: root
    group: root
    mode: 0755

- name: create confd group
  group:
    name: '{{ confd_group }}'
    state: present

- name: create confd user
  user:
    name: '{{ confd_user }}'
    group: '{{ confd_group }}'
    state: present

- name: Create needed directory
  file:
    path: "/etc/confd/{{ item }}"
    state: directory
    owner: '{{ confd_user }}'
    group: '{{ confd_group }}'
    mode: 0755
  loop:
    - conf.d
    - templates

- name: Create pgbouncer toml configuration
  template:
    src: pgbouncer.toml.j2
    dest: "/etc/confd/conf.d/pgbouncer.toml"
    owner: '{{ confd_group }}'
    group: '{{ confd_group }}'
    mode: 0644
  notify: Restart confd
  with_dict:
    "{{ clusters_config }}"

- name: Create pgbouncer tmpl configuration
  template:
    src: pgbouncer.tmpl.j2
    dest: "/etc/confd/templates/pgbouncer.tmpl"
    owner: '{{ confd_group }}'
    group: '{{ confd_group }}'
    mode: 0644
    variable_start_string: '[['
    variable_end_string: ']]'
  notify: Restart confd
  with_dict:
    "{{ clusters_config }}"

- name: Create haproxy toml configuration
  template:
    src: haproxy.toml.j2
    dest: "/etc/confd/conf.d/haproxy.toml"
    owner: '{{ confd_group }}'
    group: '{{ confd_group }}'
    mode: 0644
    variable_start_string: '[['
    variable_end_string: ']]'
  notify: Restart confd
  with_dict:
    "{{ clusters_config }}"

- name: Create haproxy tmpl configuration
  template:
    src: haproxy.tmpl.j2
    dest: "/etc/confd/templates/haproxy.tmpl"
    owner: '{{ confd_group }}'
    group: '{{ confd_group }}'
    mode: 0644
    variable_start_string: '[['
    variable_end_string: ']]'
  notify: Restart confd
  with_dict:
    "{{ clusters_config }}"


- name: Install confd.service systemd unit
  template:
    src: systemd.j2
    dest: /etc/systemd/system/confd.service
    owner: '{{ confd_group }}'
    group: '{{ confd_group }}'
    mode: 0644
  notify: Restart confd
