- name: Add security only sources.list
  apt_repository:
    repo: deb http://security.debian.org/ stable/updates main
    filename: 'security'
    state: present

- name: Update security only
  shell:
    apt update && apt-get upgrade -y --force-yes -o Dir::Etc::SourceList=/etc/apt/sources.list.d/security.list -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

- name: Update system
  apt:
    upgrade: full
    force: yes
    dpkg_options: force-confdef,force-confold
    autoremove: yes
    install_recommends: no
